/**
 * Deterministic 0.10 retrieval corpus.
 *
 * These are deliberately small structural cases.  The vectors are hand-authored
 * four-dimensional signals: a direct seed is close to contextVector while a
 * relation-only record is orthogonal to it.  Text is ordinary source-like text;
 * no fixture embeds an evaluation answer or depends on a ranking implementation.
 * Every budget is written out so that comparisons use the same declared windows.
 */

export const fixtures = [
  {
    id: 'relation-only-2-hop',
    description: 'A direct release note reaches a supporting record through one bridge.',
    nodes: [
      {
        id: 'root-note',
        text: 'Autumn deployment review notes.',
        vector: [1, 0.08, 0, 0],
        links: [{ to: 'bridge-note', role: 'supports' }],
      },
      {
        id: 'bridge-note',
        text: 'Operations handoff record.',
        vector: [0, 1, 0, 0],
        links: [{ to: 'evidence-note', role: 'supports' }],
      },
      {
        id: 'evidence-note',
        text: 'Signed archival ledger.',
        vector: [0, 0, 1, 0],
      },
    ],
    seeds: ['root-note'],
    context: 'A deployment review needs one supporting record.',
    contextVector: [1, 0, 0, 0],
    evidence: ['evidence-note'],
    depth: 2,
    tokens: 8000,
    budgets: [
      {
        name: 'quality',
        budget: {
          maxCandidates: 256,
          maxBytes: 262144,
          maxAtoms: 32,
          maxContextTokens: 8000,
          maxEvaluationWork: 200000,
          maxPackingWork: 200000,
        },
      },
      {
        name: 'stress-evaluation',
        tokens: 120,
        budget: {
          maxCandidates: 24,
          maxBytes: 18000,
          maxAtoms: 12,
          maxContextTokens: 160,
          maxEvaluationWork: 900,
          maxPackingWork: 90,
        },
      },
      {
        name: 'acquisition-tight',
        tokens: 120,
        budget: {
          maxCandidates: 8,
          maxBytes: 9000,
          maxAtoms: 8,
          maxContextTokens: 160,
          maxEvaluationWork: 600,
          maxPackingWork: 60,
        },
      },
      {
        name: 'packing-tight',
        tokens: 120,
        budget: {
          maxCandidates: 24,
          maxBytes: 18000,
          maxAtoms: 12,
          maxContextTokens: 24,
          maxEvaluationWork: 900,
          maxPackingWork: 60,
        },
      },
    ],
    relations: { supports: { forward: 1, reverse: 0.8 } },
    tags: ['relation-only', 'two-hop'],
  },

  {
    id: 'relation-only-3-hop',
    description: 'A maintenance note reaches a supporting record through two bridges.',
    nodes: [
      {
        id: 'root-note',
        text: 'Maintenance window notes.',
        vector: [1, 0.1, 0, 0],
        links: [{ to: 'bridge-one', role: 'supports' }],
      },
      {
        id: 'bridge-one',
        text: 'Service handoff register.',
        vector: [0, 1, 0, 0],
        links: [{ to: 'bridge-two', role: 'supports' }],
      },
      {
        id: 'bridge-two',
        text: 'On-call rotation ledger.',
        vector: [0, 0, 1, 0],
        links: [{ to: 'evidence-note', role: 'supports' }],
      },
      {
        id: 'evidence-note',
        text: 'Approved service checksum.',
        vector: [0, 0, 0, 1],
      },
    ],
    seeds: ['root-note'],
    context: 'A maintenance review needs one supporting record.',
    contextVector: [1, 0, 0, 0],
    evidence: ['evidence-note'],
    depth: 3,
    tokens: 8000,
    budgets: [
      {
        name: 'quality',
        budget: {
          maxCandidates: 256,
          maxBytes: 262144,
          maxAtoms: 32,
          maxContextTokens: 8000,
          maxEvaluationWork: 200000,
          maxPackingWork: 200000,
        },
      },
      {
        name: 'stress-evaluation',
        tokens: 140,
        budget: {
          maxCandidates: 32,
          maxBytes: 22000,
          maxAtoms: 16,
          maxContextTokens: 180,
          maxEvaluationWork: 1100,
          maxPackingWork: 100,
        },
      },
      {
        name: 'acquisition-tight',
        tokens: 140,
        budget: {
          maxCandidates: 10,
          maxBytes: 10000,
          maxAtoms: 10,
          maxContextTokens: 180,
          maxEvaluationWork: 700,
          maxPackingWork: 70,
        },
      },
      {
        name: 'packing-tight',
        tokens: 140,
        budget: {
          maxCandidates: 32,
          maxBytes: 22000,
          maxAtoms: 16,
          maxContextTokens: 28,
          maxEvaluationWork: 1100,
          maxPackingWork: 70,
        },
      },
    ],
    relations: { supports: { forward: 1, reverse: 0.8 } },
    tags: ['relation-only', 'three-hop'],
  },

  {
    id: 'relation-only-4-hop',
    description: 'A governance note reaches a supporting record through three bridges.',
    nodes: [
      {
        id: 'root-note',
        text: 'Governance review notes.',
        vector: [1, 0.08, 0, 0],
        links: [{ to: 'bridge-one', role: 'supports' }],
      },
      {
        id: 'bridge-one',
        text: 'Policy handoff register.',
        vector: [0, 1, 0, 0],
        links: [{ to: 'bridge-two', role: 'supports' }],
      },
      {
        id: 'bridge-two',
        text: 'Review meeting ledger.',
        vector: [0, 0, 1, 0],
        links: [{ to: 'bridge-three', role: 'supports' }],
      },
      {
        id: 'bridge-three',
        text: 'Steward contact register.',
        vector: [0, 0, 0, 1],
        links: [{ to: 'evidence-note', role: 'supports' }],
      },
      {
        id: 'evidence-note',
        text: 'Signed access ledger.',
        vector: [0, 0, 1, 0],
      },
    ],
    seeds: ['root-note'],
    context: 'A governance review needs one supporting record.',
    contextVector: [1, 0, 0, 0],
    evidence: ['evidence-note'],
    depth: 4,
    tokens: 8000,
    budgets: [
      {
        name: 'quality',
        budget: {
          maxCandidates: 256,
          maxBytes: 262144,
          maxAtoms: 32,
          maxContextTokens: 8000,
          maxEvaluationWork: 200000,
          maxPackingWork: 200000,
        },
      },
      {
        name: 'stress-evaluation',
        tokens: 160,
        budget: {
          maxCandidates: 40,
          maxBytes: 26000,
          maxAtoms: 20,
          maxContextTokens: 200,
          maxEvaluationWork: 1300,
          maxPackingWork: 120,
        },
      },
      {
        name: 'acquisition-tight',
        tokens: 160,
        budget: {
          maxCandidates: 12,
          maxBytes: 12000,
          maxAtoms: 12,
          maxContextTokens: 200,
          maxEvaluationWork: 800,
          maxPackingWork: 80,
        },
      },
      {
        name: 'packing-tight',
        tokens: 160,
        budget: {
          maxCandidates: 40,
          maxBytes: 26000,
          maxAtoms: 20,
          maxContextTokens: 32,
          maxEvaluationWork: 1300,
          maxPackingWork: 80,
        },
      },
    ],
    relations: { supports: { forward: 1, reverse: 0.8 } },
    tags: ['relation-only', 'four-hop'],
  },

  {
    id: 'hub-low-matching-bridge',
    description: 'A high-degree note has many irrelevant neighbors and one low-matching bridge.',
    nodes: [
      {
        id: 'hub-note',
        text: 'Regional operations index.',
        vector: [1, 0.1, 0, 0],
        links: [
          { to: 'noise-01', role: 'noise' },
          { to: 'noise-02', role: 'noise' },
          { to: 'noise-03', role: 'noise' },
          { to: 'noise-04', role: 'noise' },
          { to: 'noise-05', role: 'noise' },
          { to: 'noise-06', role: 'noise' },
          { to: 'noise-07', role: 'noise' },
          { to: 'noise-08', role: 'noise' },
          { to: 'noise-09', role: 'noise' },
          { to: 'noise-10', role: 'noise' },
          { to: 'noise-11', role: 'noise' },
          { to: 'noise-12', role: 'noise' },
          { to: 'noise-13', role: 'noise' },
          { to: 'noise-14', role: 'noise' },
          { to: 'noise-15', role: 'noise' },
          { to: 'noise-16', role: 'noise' },
          { to: 'noise-17', role: 'noise' },
          { to: 'noise-18', role: 'noise' },
          { to: 'noise-19', role: 'noise' },
          { to: 'noise-20', role: 'noise' },
          { to: 'bridge-note', role: 'support' },
        ],
      },
      { id: 'noise-01', text: 'Facilities key register.', vector: [0, 0, 1, 0] },
      { id: 'noise-02', text: 'Travel desk opening hours.', vector: [0, 0, 1, 0] },
      { id: 'noise-03', text: 'Catering supplier list.', vector: [0, 0, 1, 0] },
      { id: 'noise-04', text: 'Parking allocation sheet.', vector: [0, 0, 1, 0] },
      { id: 'noise-05', text: 'Office plant schedule.', vector: [0, 0, 1, 0] },
      { id: 'noise-06', text: 'Printer maintenance log.', vector: [0, 0, 1, 0] },
      { id: 'noise-07', text: 'Visitor badge inventory.', vector: [0, 0, 1, 0] },
      { id: 'noise-08', text: 'Courier pickup rota.', vector: [0, 0, 1, 0] },
      { id: 'noise-09', text: 'Building access map.', vector: [0, 0, 1, 0] },
      { id: 'noise-10', text: 'Meeting room equipment list.', vector: [0, 0, 1, 0] },
      { id: 'noise-11', text: 'Security desk timetable.', vector: [0, 0, 1, 0] },
      { id: 'noise-12', text: 'Cleaning service roster.', vector: [0, 0, 1, 0] },
      { id: 'noise-13', text: 'Emergency drill calendar.', vector: [0, 0, 1, 0] },
      { id: 'noise-14', text: 'Storage cabinet map.', vector: [0, 0, 1, 0] },
      { id: 'noise-15', text: 'Heating control checklist.', vector: [0, 0, 1, 0] },
      { id: 'noise-16', text: 'Reception shift ledger.', vector: [0, 0, 1, 0] },
      { id: 'noise-17', text: 'Bicycle rack survey.', vector: [0, 0, 1, 0] },
      { id: 'noise-18', text: 'Waste collection timetable.', vector: [0, 0, 1, 0] },
      { id: 'noise-19', text: 'Lighting inspection sheet.', vector: [0, 0, 1, 0] },
      { id: 'noise-20', text: 'Kitchen stock ledger.', vector: [0, 0, 1, 0] },
      {
        id: 'bridge-note',
        text: 'Cross-region incident handoff.',
        vector: [0.45, 0.89, 0, 0],
        links: [{ to: 'useful-record', role: 'support' }],
      },
      {
        id: 'useful-record',
        text: 'Authorization ledger entry.',
        vector: [0, 1, 0, 0],
      },
    ],
    seeds: ['hub-note'],
    context: 'An operations review needs the escalation record.',
    contextVector: [1, 0, 0, 0],
    evidence: ['useful-record'],
    depth: 2,
    tokens: 8000,
    budgets: [
      {
        name: 'quality',
        budget: {
          maxCandidates: 256,
          maxBytes: 262144,
          maxAtoms: 32,
          maxContextTokens: 8000,
          maxEvaluationWork: 200000,
          maxPackingWork: 200000,
        },
      },
      {
        name: 'stress-evaluation',
        tokens: 150,
        budget: {
          maxCandidates: 72,
          maxBytes: 50000,
          maxAtoms: 40,
          maxContextTokens: 220,
          maxEvaluationWork: 2600,
          maxPackingWork: 220,
        },
      },
      {
        name: 'hub-tight',
        tokens: 150,
        budget: {
          maxCandidates: 24,
          maxBytes: 22000,
          maxAtoms: 16,
          maxContextTokens: 220,
          maxEvaluationWork: 1200,
          maxPackingWork: 120,
        },
      },
      {
        name: 'packing-tight',
        tokens: 150,
        budget: {
          maxCandidates: 72,
          maxBytes: 50000,
          maxAtoms: 40,
          maxContextTokens: 28,
          maxEvaluationWork: 2600,
          maxPackingWork: 120,
        },
      },
    ],
    relations: {
      noise: { forward: 0.05, reverse: 0.05 },
      support: { forward: 1, reverse: 0.2 },
    },
    tags: ['hub', 'low-matching-bridge', 'irrelevant-neighbors'],
  },

  {
    id: 'shared-mandatory-condition',
    description: 'Two entries share one mandatory companion record.',
    nodes: [
      {
        id: 'entry-a',
        text: 'Regional launch entry.',
        vector: [1, 0.1, 0, 0],
        links: [{ to: 'shared-condition', role: 'condition', required: true }],
      },
      {
        id: 'entry-b',
        text: 'Partner launch entry.',
        vector: [0.96, 0.2, 0, 0],
        links: [{ to: 'shared-condition', role: 'condition', required: true }],
      },
      {
        id: 'shared-condition',
        text: 'Administrative seal archived.',
        vector: [0, 1, 0, 0],
      },
      { id: 'unrelated-entry', text: 'Office supply request.', vector: [0, 0, 1, 0] },
    ],
    seeds: ['entry-a', 'entry-b'],
    context: 'A launch record needs its shared approval condition.',
    contextVector: [1, 0, 0, 0],
    evidence: ['shared-condition'],
    depth: 1,
    tokens: 8000,
    budgets: [
      {
        name: 'quality',
        budget: {
          maxCandidates: 256,
          maxBytes: 262144,
          maxAtoms: 32,
          maxContextTokens: 8000,
          maxEvaluationWork: 200000,
          maxPackingWork: 200000,
        },
      },
      {
        name: 'stress-evaluation',
        tokens: 120,
        budget: {
          maxCandidates: 28,
          maxBytes: 20000,
          maxAtoms: 12,
          maxContextTokens: 160,
          maxEvaluationWork: 1000,
          maxPackingWork: 100,
        },
      },
      {
        name: 'condition-tight',
        tokens: 120,
        budget: {
          maxCandidates: 8,
          maxBytes: 9000,
          maxAtoms: 8,
          maxContextTokens: 160,
          maxEvaluationWork: 650,
          maxPackingWork: 70,
        },
      },
      {
        name: 'packing-tight',
        tokens: 120,
        budget: {
          maxCandidates: 28,
          maxBytes: 20000,
          maxAtoms: 12,
          maxContextTokens: 20,
          maxEvaluationWork: 1000,
          maxPackingWork: 70,
        },
      },
    ],
    relations: { condition: { forward: 1, reverse: 0.25 } },
    conditionPairs: [
      ['entry-a', 'shared-condition'],
      ['entry-b', 'shared-condition'],
    ],
    tags: ['shared-condition', 'mandatory', 'required-edge'],
  },

  {
    id: 'popular-topic-to-novel-context',
    description: 'A frequently accepted topic sits beside a newer contextual route.',
    nodes: [
      {
        id: 'popular-topic',
        text: 'Annual launch checklist.',
        vector: [0.98, 0.2, 0, 0],
        links: [{ to: 'novel-anchor', role: 'related' }],
      },
      {
        id: 'novel-anchor',
        text: 'Small regional pilot notes.',
        vector: [0.45, 0.89, 0, 0],
        links: [{ to: 'novel-evidence', role: 'related' }],
      },
      {
        id: 'novel-evidence',
        text: 'Signed authorization ledger.',
        vector: [0, 1, 0, 0],
      },
      { id: 'stable-background', text: 'Archived office calendar.', vector: [0, 0, 1, 0] },
    ],
    seeds: ['popular-topic', 'novel-anchor'],
    context: 'A new regional pilot needs its owner record.',
    contextVector: [1, 0, 0, 0],
    acceptedUses: [
      { id: 'popular-topic', count: 8 },
      { id: 'novel-anchor', count: 1 },
      { id: 'novel-evidence', count: 0 },
    ],
    evidence: ['novel-evidence'],
    depth: 2,
    tokens: 8000,
    budgets: [
      {
        name: 'quality',
        budget: {
          maxCandidates: 256,
          maxBytes: 262144,
          maxAtoms: 32,
          maxContextTokens: 8000,
          maxEvaluationWork: 200000,
          maxPackingWork: 200000,
        },
      },
      {
        name: 'stress-evaluation',
        tokens: 130,
        budget: {
          maxCandidates: 32,
          maxBytes: 22000,
          maxAtoms: 14,
          maxContextTokens: 180,
          maxEvaluationWork: 1100,
          maxPackingWork: 100,
        },
      },
      {
        name: 'usage-tight',
        tokens: 130,
        budget: {
          maxCandidates: 10,
          maxBytes: 10000,
          maxAtoms: 10,
          maxContextTokens: 180,
          maxEvaluationWork: 700,
          maxPackingWork: 70,
        },
      },
      {
        name: 'packing-tight',
        tokens: 130,
        budget: {
          maxCandidates: 32,
          maxBytes: 22000,
          maxAtoms: 14,
          maxContextTokens: 24,
          maxEvaluationWork: 1100,
          maxPackingWork: 70,
        },
      },
    ],
    relations: { related: { forward: 1, reverse: 0.7 } },
    tags: ['accepted-use', 'popular-to-novel', 'context-switch'],
  },

  {
    id: 'cycles-and-multiple-paths',
    description: 'A small graph contains a cycle and two routes to one record.',
    nodes: [
      {
        id: 'root-note',
        text: 'Incident review index.',
        vector: [1, 0.08, 0, 0],
        links: [
          { to: 'route-a', role: 'related' },
          { to: 'route-b', role: 'related' },
          { to: 'shared-node', role: 'related' },
        ],
      },
      {
        id: 'route-a',
        text: 'First response ledger.',
        vector: [0, 1, 0, 0],
        links: [
          { to: 'shared-node', role: 'related' },
          { to: 'route-b', role: 'related' },
        ],
      },
      {
        id: 'route-b',
        text: 'Second response ledger.',
        vector: [0, 0, 1, 0],
        links: [
          { to: 'route-a', role: 'related' },
          { to: 'shared-node', role: 'related' },
        ],
      },
      {
        id: 'shared-node',
        text: 'Escalation handoff record.',
        vector: [0, 0, 0, 1],
        links: [{ to: 'evidence-note', role: 'related' }],
      },
      { id: 'evidence-note', text: 'Custodian signature ledger.', vector: [0, 1, 0, 0] },
    ],
    seeds: ['root-note'],
    context: 'An incident review needs the owner sign-off.',
    contextVector: [1, 0, 0, 0],
    evidence: ['evidence-note'],
    depth: 3,
    tokens: 8000,
    budgets: [
      {
        name: 'quality',
        budget: {
          maxCandidates: 256,
          maxBytes: 262144,
          maxAtoms: 32,
          maxContextTokens: 8000,
          maxEvaluationWork: 200000,
          maxPackingWork: 200000,
        },
      },
      {
        name: 'stress-evaluation',
        tokens: 150,
        budget: {
          maxCandidates: 40,
          maxBytes: 28000,
          maxAtoms: 20,
          maxContextTokens: 200,
          maxEvaluationWork: 1500,
          maxPackingWork: 130,
        },
      },
      {
        name: 'cycle-tight',
        tokens: 150,
        budget: {
          maxCandidates: 12,
          maxBytes: 12000,
          maxAtoms: 12,
          maxContextTokens: 200,
          maxEvaluationWork: 900,
          maxPackingWork: 80,
        },
      },
      {
        name: 'packing-tight',
        tokens: 150,
        budget: {
          maxCandidates: 40,
          maxBytes: 28000,
          maxAtoms: 20,
          maxContextTokens: 26,
          maxEvaluationWork: 1500,
          maxPackingWork: 80,
        },
      },
    ],
    relations: { related: { forward: 0.9, reverse: 0.9 } },
    tags: ['cycle', 'multiple-paths', 'shared-target'],
  },

  {
    id: 'graph-growth-normalization',
    description: 'A late branch adds a second contribution to an already reachable record.',
    nodes: [
      {
        id: 'growth-root',
        text: 'Release coordination index.',
        vector: [1, 0.1, 0, 0],
        links: [
          { to: 'early-branch', role: 'branch' },
          { to: 'late-branch', role: 'branch' },
        ],
      },
      {
        id: 'early-branch',
        text: 'Initial coordination note.',
        vector: [0, 1, 0, 0],
        links: [{ to: 'shared-record', role: 'branch' }],
      },
      {
        id: 'late-branch',
        text: 'Follow-up coordination note.',
        vector: [0.35, 0.94, 0, 0],
        links: [{ to: 'shared-record', role: 'branch' }],
      },
      { id: 'shared-record', text: 'Control ledger entry.', vector: [0, 0, 1, 0] },
      { id: 'unrelated-record', text: 'Cafeteria closing checklist.', vector: [0, 0, 0, 1] },
    ],
    seeds: ['growth-root'],
    context: 'A release review needs the owner confirmation.',
    contextVector: [1, 0, 0, 0],
    evidence: ['shared-record'],
    depth: 2,
    tokens: 8000,
    budgets: [
      {
        name: 'quality',
        budget: {
          maxCandidates: 256,
          maxBytes: 262144,
          maxAtoms: 32,
          maxContextTokens: 8000,
          maxEvaluationWork: 200000,
          maxPackingWork: 200000,
        },
      },
      {
        name: 'stress-evaluation',
        tokens: 130,
        budget: {
          maxCandidates: 36,
          maxBytes: 25000,
          maxAtoms: 18,
          maxContextTokens: 180,
          maxEvaluationWork: 1300,
          maxPackingWork: 110,
        },
      },
      {
        name: 'growth-tight',
        tokens: 130,
        budget: {
          maxCandidates: 10,
          maxBytes: 10000,
          maxAtoms: 10,
          maxContextTokens: 180,
          maxEvaluationWork: 750,
          maxPackingWork: 70,
        },
      },
      {
        name: 'packing-tight',
        tokens: 130,
        budget: {
          maxCandidates: 36,
          maxBytes: 25000,
          maxAtoms: 18,
          maxContextTokens: 24,
          maxEvaluationWork: 1300,
          maxPackingWork: 70,
        },
      },
    ],
    relations: { branch: { forward: 1, reverse: 0.6 } },
    tags: ['graph-growth', 'normalization', 'late-edge'],
  },

  {
    id: 'small-direct-answer-control',
    description: 'The candidate already contains the only useful record.',
    nodes: [
      { id: 'direct-record', text: 'Direct deployment owner note.', vector: [1, 0.05, 0, 0] },
      { id: 'background-record', text: 'Archived room booking.', vector: [0, 0, 1, 0] },
    ],
    seeds: ['direct-record'],
    context: 'A deployment review needs the owner note.',
    contextVector: [1, 0, 0, 0],
    evidence: ['direct-record'],
    depth: 0,
    tokens: 8000,
    budgets: [
      {
        name: 'quality',
        budget: {
          maxCandidates: 256,
          maxBytes: 262144,
          maxAtoms: 32,
          maxContextTokens: 8000,
          maxEvaluationWork: 200000,
          maxPackingWork: 200000,
        },
      },
      {
        name: 'stress-evaluation',
        tokens: 80,
        budget: {
          maxCandidates: 12,
          maxBytes: 10000,
          maxAtoms: 8,
          maxContextTokens: 120,
          maxEvaluationWork: 500,
          maxPackingWork: 40,
        },
      },
      {
        name: 'minimal',
        tokens: 80,
        budget: {
          maxCandidates: 4,
          maxBytes: 5000,
          maxAtoms: 4,
          maxContextTokens: 120,
          maxEvaluationWork: 300,
          maxPackingWork: 24,
        },
      },
      {
        name: 'packing-tight',
        tokens: 80,
        budget: {
          maxCandidates: 12,
          maxBytes: 10000,
          maxAtoms: 8,
          maxContextTokens: 12,
          maxEvaluationWork: 500,
          maxPackingWork: 24,
        },
      },
    ],
    tags: ['control', 'candidate-only', 'direct'],
  },

  {
    id: 'candidate-only-multi-control',
    description: 'Two directly matched records are sufficient without graph expansion.',
    nodes: [
      { id: 'direct-record-a', text: 'Primary owner note.', vector: [1, 0.05, 0, 0] },
      { id: 'direct-record-b', text: 'Secondary owner note.', vector: [0.98, 0.18, 0, 0] },
      { id: 'background-record', text: 'Archived supplies note.', vector: [0, 0, 1, 0] },
    ],
    seeds: ['direct-record-a', 'direct-record-b'],
    context: 'An owner review needs the two directly matched notes.',
    contextVector: [1, 0, 0, 0],
    evidence: ['direct-record-a', 'direct-record-b'],
    depth: 0,
    tokens: 8000,
    budgets: [
      {
        name: 'quality',
        budget: {
          maxCandidates: 256,
          maxBytes: 262144,
          maxAtoms: 32,
          maxContextTokens: 8000,
          maxEvaluationWork: 200000,
          maxPackingWork: 200000,
        },
      },
      {
        name: 'stress-evaluation',
        tokens: 100,
        budget: {
          maxCandidates: 16,
          maxBytes: 12000,
          maxAtoms: 10,
          maxContextTokens: 140,
          maxEvaluationWork: 600,
          maxPackingWork: 50,
        },
      },
      {
        name: 'minimal',
        tokens: 100,
        budget: {
          maxCandidates: 5,
          maxBytes: 6000,
          maxAtoms: 5,
          maxContextTokens: 140,
          maxEvaluationWork: 350,
          maxPackingWork: 30,
        },
      },
      {
        name: 'packing-tight',
        tokens: 100,
        budget: {
          maxCandidates: 16,
          maxBytes: 12000,
          maxAtoms: 10,
          maxContextTokens: 18,
          maxEvaluationWork: 600,
          maxPackingWork: 30,
        },
      },
    ],
    tags: ['control', 'candidate-only', 'multiple-direct'],
  },

  {
    id: 'long-then-short-path',
    description:
      'The first stored route is long while a later route reaches the same record sooner.',
    nodes: [
      {
        id: 'path-root',
        text: 'Release route index.',
        vector: [1, 0.08, 0, 0],
        links: [
          { to: 'long-one', role: 'route' },
          { to: 'short-one', role: 'route' },
        ],
      },
      {
        id: 'long-one',
        text: 'Long route checkpoint one.',
        vector: [0, 1, 0, 0],
        links: [{ to: 'long-two', role: 'route' }],
      },
      {
        id: 'long-two',
        text: 'Long route checkpoint two.',
        vector: [0, 0, 1, 0],
        links: [{ to: 'shared-record', role: 'route' }],
      },
      {
        id: 'short-one',
        text: 'Short route checkpoint.',
        vector: [0.35, 0.94, 0, 0],
        links: [{ to: 'shared-record', role: 'route' }],
      },
      { id: 'shared-record', text: 'Custodian authorization ledger.', vector: [0, 0, 0, 1] },
    ],
    seeds: ['path-root'],
    context: 'A release review needs the shared owner confirmation.',
    contextVector: [1, 0, 0, 0],
    evidence: ['shared-record'],
    depth: 4,
    tokens: 8000,
    budgets: [
      {
        name: 'quality',
        budget: {
          maxCandidates: 256,
          maxBytes: 262144,
          maxAtoms: 32,
          maxContextTokens: 8000,
          maxEvaluationWork: 200000,
          maxPackingWork: 200000,
        },
      },
      {
        name: 'stress-evaluation',
        tokens: 140,
        budget: {
          maxCandidates: 36,
          maxBytes: 25000,
          maxAtoms: 18,
          maxContextTokens: 190,
          maxEvaluationWork: 1300,
          maxPackingWork: 110,
        },
      },
      {
        name: 'depth-tight',
        tokens: 140,
        budget: {
          maxCandidates: 10,
          maxBytes: 10000,
          maxAtoms: 10,
          maxContextTokens: 190,
          maxEvaluationWork: 750,
          maxPackingWork: 70,
        },
      },
      {
        name: 'packing-tight',
        tokens: 140,
        budget: {
          maxCandidates: 36,
          maxBytes: 25000,
          maxAtoms: 18,
          maxContextTokens: 24,
          maxEvaluationWork: 1300,
          maxPackingWork: 70,
        },
      },
    ],
    relations: { route: { forward: 1, reverse: 0.75 } },
    tags: ['long-then-short', 'depth-relaxation', 'multiple-paths'],
  },

  {
    id: 'zero-reverse-incoming-direct-seed',
    description:
      'An incoming neighbor is a strong direct seed while reverse propagation is disabled.',
    nodes: [
      {
        id: 'target-record',
        text: 'Incident review note.',
        vector: [1, 0.04, 0, 0],
      },
      {
        id: 'incoming-neighbor',
        text: 'Control ledger entry.',
        vector: [1, 0.02, 0, 0],
        links: [{ to: 'target-record', role: 'one-way' }],
      },
      { id: 'background-record', text: 'Archived travel note.', vector: [0, 0, 1, 0] },
    ],
    seeds: ['target-record'],
    context: 'An incident review starts from a directly matched note.',
    contextVector: [1, 0, 0, 0],
    evidence: ['incoming-neighbor'],
    depth: 1,
    tokens: 8000,
    budgets: [
      {
        name: 'quality',
        budget: {
          maxCandidates: 256,
          maxBytes: 262144,
          maxAtoms: 32,
          maxContextTokens: 8000,
          maxEvaluationWork: 200000,
          maxPackingWork: 200000,
        },
      },
      {
        name: 'stress-evaluation',
        tokens: 110,
        budget: {
          maxCandidates: 20,
          maxBytes: 16000,
          maxAtoms: 10,
          maxContextTokens: 150,
          maxEvaluationWork: 750,
          maxPackingWork: 70,
        },
      },
      {
        name: 'reverse-tight',
        tokens: 110,
        budget: {
          maxCandidates: 6,
          maxBytes: 7000,
          maxAtoms: 6,
          maxContextTokens: 150,
          maxEvaluationWork: 450,
          maxPackingWork: 45,
        },
      },
      {
        name: 'packing-tight',
        tokens: 110,
        budget: {
          maxCandidates: 20,
          maxBytes: 16000,
          maxAtoms: 10,
          maxContextTokens: 16,
          maxEvaluationWork: 750,
          maxPackingWork: 45,
        },
      },
    ],
    relations: { 'one-way': { forward: 1, reverse: 0 } },
    tags: ['zero-reverse', 'incoming-neighbor', 'direct-seed'],
  },

  {
    id: 'oversized-bridge-compact-evidence',
    description:
      'A large bridge is traversable but a compact downstream record fits the display window.',
    nodes: [
      {
        id: 'root-note',
        text: 'Operations review index.',
        vector: [1, 0.08, 0, 0],
        links: [{ to: 'large-bridge', role: 'supports' }],
      },
      {
        id: 'large-bridge',
        text: `The operations archive contains the handoff history for the regional service.\nIt records each checkpoint, steward, contact window, escalation note, and follow-up entry.\nThe same register includes routine scheduling details, meeting references, facility notes, and\ncross-team acknowledgements retained for audit continuity. This bridge is intentionally longer\nthan the display window, while its links point to a small record that can be shown directly.\nThe archive also preserves dates, internal routing labels, review comments, and old checklist\nreferences so that a later inspection can reconstruct the sequence without changing the source.`,
        vector: [0, 1, 0, 0],
        links: [{ to: 'compact-evidence', role: 'supports', required: true }],
      },
      {
        id: 'compact-evidence',
        text: 'Seal logged at 09:00.',
        vector: [0, 0, 1, 0],
      },
      { id: 'background-record', text: 'Archived room booking.', vector: [0, 0, 0, 1] },
    ],
    seeds: ['root-note'],
    context: 'An operations review needs the compact owner approval record.',
    contextVector: [1, 0, 0, 0],
    evidence: ['compact-evidence'],
    depth: 2,
    tokens: 8000,
    budgets: [
      {
        name: 'quality',
        budget: {
          maxCandidates: 256,
          maxBytes: 262144,
          maxAtoms: 32,
          maxContextTokens: 8000,
          maxEvaluationWork: 200000,
          maxPackingWork: 200000,
        },
      },
      {
        name: 'stress-evaluation',
        tokens: 48,
        budget: {
          maxCandidates: 24,
          maxBytes: 24000,
          maxAtoms: 12,
          maxContextTokens: 160,
          maxEvaluationWork: 900,
          maxPackingWork: 90,
        },
      },
      {
        name: 'display-tight',
        tokens: 48,
        budget: {
          maxCandidates: 8,
          maxBytes: 18000,
          maxAtoms: 8,
          maxContextTokens: 48,
          maxEvaluationWork: 600,
          maxPackingWork: 60,
        },
      },
      {
        name: 'packing-tight',
        tokens: 48,
        budget: {
          maxCandidates: 24,
          maxBytes: 24000,
          maxAtoms: 12,
          maxContextTokens: 20,
          maxEvaluationWork: 900,
          maxPackingWork: 60,
        },
      },
    ],
    relations: { supports: { forward: 1, reverse: 0.7 } },
    tags: ['oversized-bridge', 'compact-evidence', 'display-budget'],
  },

  {
    id: 'order-permutation-a',
    description: 'Baseline outgoing order for three equivalent routes to one record.',
    nodes: [
      {
        id: 'order-root',
        text: 'Route order index.',
        vector: [1, 0.08, 0, 0],
        links: [
          { to: 'route-first', role: 'route' },
          { to: 'route-second', role: 'route' },
          { to: 'route-third', role: 'route' },
        ],
      },
      {
        id: 'route-first',
        text: 'First route note.',
        vector: [0, 1, 0, 0],
        links: [{ to: 'order-evidence', role: 'route' }],
      },
      {
        id: 'route-second',
        text: 'Second route note.',
        vector: [0, 0, 1, 0],
        links: [{ to: 'order-evidence', role: 'route' }],
      },
      {
        id: 'route-third',
        text: 'Third route note.',
        vector: [0, 0, 0, 1],
        links: [{ to: 'order-evidence', role: 'route' }],
      },
      { id: 'order-evidence', text: 'Custodian seal ledger.', vector: [0, 1, 0, 0] },
    ],
    seeds: ['order-root'],
    context: 'A route review needs the owner approval.',
    contextVector: [1, 0, 0, 0],
    evidence: ['order-evidence'],
    depth: 2,
    tokens: 8000,
    budgets: [
      {
        name: 'quality',
        budget: {
          maxCandidates: 256,
          maxBytes: 262144,
          maxAtoms: 32,
          maxContextTokens: 8000,
          maxEvaluationWork: 200000,
          maxPackingWork: 200000,
        },
      },
      {
        name: 'stress-evaluation',
        tokens: 130,
        budget: {
          maxCandidates: 32,
          maxBytes: 22000,
          maxAtoms: 16,
          maxContextTokens: 180,
          maxEvaluationWork: 1100,
          maxPackingWork: 100,
        },
      },
      {
        name: 'order-tight',
        tokens: 130,
        budget: {
          maxCandidates: 8,
          maxBytes: 9000,
          maxAtoms: 8,
          maxContextTokens: 180,
          maxEvaluationWork: 650,
          maxPackingWork: 60,
        },
      },
      {
        name: 'packing-tight',
        tokens: 130,
        budget: {
          maxCandidates: 32,
          maxBytes: 22000,
          maxAtoms: 16,
          maxContextTokens: 22,
          maxEvaluationWork: 1100,
          maxPackingWork: 60,
        },
      },
    ],
    relations: { route: { forward: 1, reverse: 0.6 } },
    tags: ['order-permutation', 'adversarial-order', 'permutation-a'],
  },

  {
    id: 'order-permutation-b',
    description: 'The same routes and evidence with a different stored outgoing order.',
    nodes: [
      {
        id: 'order-root',
        text: 'Route order index.',
        vector: [1, 0.08, 0, 0],
        links: [
          { to: 'route-third', role: 'route' },
          { to: 'route-first', role: 'route' },
          { to: 'route-second', role: 'route' },
        ],
      },
      {
        id: 'route-first',
        text: 'First route note.',
        vector: [0, 1, 0, 0],
        links: [{ to: 'order-evidence', role: 'route' }],
      },
      {
        id: 'route-second',
        text: 'Second route note.',
        vector: [0, 0, 1, 0],
        links: [{ to: 'order-evidence', role: 'route' }],
      },
      {
        id: 'route-third',
        text: 'Third route note.',
        vector: [0, 0, 0, 1],
        links: [{ to: 'order-evidence', role: 'route' }],
      },
      { id: 'order-evidence', text: 'Custodian seal ledger.', vector: [0, 1, 0, 0] },
    ],
    seeds: ['order-root'],
    context: 'A route review needs the owner approval.',
    contextVector: [1, 0, 0, 0],
    evidence: ['order-evidence'],
    depth: 2,
    tokens: 8000,
    budgets: [
      {
        name: 'quality',
        budget: {
          maxCandidates: 256,
          maxBytes: 262144,
          maxAtoms: 32,
          maxContextTokens: 8000,
          maxEvaluationWork: 200000,
          maxPackingWork: 200000,
        },
      },
      {
        name: 'stress-evaluation',
        tokens: 130,
        budget: {
          maxCandidates: 32,
          maxBytes: 22000,
          maxAtoms: 16,
          maxContextTokens: 180,
          maxEvaluationWork: 1100,
          maxPackingWork: 100,
        },
      },
      {
        name: 'order-tight',
        tokens: 130,
        budget: {
          maxCandidates: 8,
          maxBytes: 9000,
          maxAtoms: 8,
          maxContextTokens: 180,
          maxEvaluationWork: 650,
          maxPackingWork: 60,
        },
      },
      {
        name: 'packing-tight',
        tokens: 130,
        budget: {
          maxCandidates: 32,
          maxBytes: 22000,
          maxAtoms: 16,
          maxContextTokens: 22,
          maxEvaluationWork: 1100,
          maxPackingWork: 60,
        },
      },
    ],
    relations: { route: { forward: 1, reverse: 0.6 } },
    tags: ['order-permutation', 'adversarial-order', 'permutation-b'],
  },
];

export default fixtures;
